class MyException extends Exception {
    private String Teks;

    MyException(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws java.lang.Exception {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new java.lang.Exception(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws java.lang.Exception {
        try {
            tampil("ali");
            tampil("amir");
        } catch (java.lang.Exception ex) {
            System.out.println("Tangkap:" + ex);
        }
    }
}
